# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Vikas Vasireddy
title: Software Engineer / ML Engineer
email: vikasvasireddy264@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  vikasvasireddy01
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: vikasvasireddy
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fa-solid fa-circle-envelope
#   url: vikasvasireddy264@gmail.com

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/avatar3.jpeg
about_content: | # this will include new lines to allow paragraphs
 I am an experienced software engineer with expertise in software engineering and machine learning. I have a proven track record in designing, developing, and scaling microservices, as well as integrating advanced messaging systems and APIs for enhanced data analytics and system performance. 
  Currently, I am a graduate assistant at Arizona State University, focusing on computing on AI and ML. Previously, I worked at Cisco, where I managed the daily dispatch of millions of messages and engineered solutions that significantly improved system responsiveness and scalability.
  On this website, you can learn more about my skills, experience, and interests, and get in touch with me to discuss potential opportunities or collaborations.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Elastic Cloud Image Processing Solution  
        additional_links:
          - title:  fingpt.info
            icon: fab fa-github
            url: https://github.com/USFCA-courses/final-project-maneelusf
          
        description: | # this will include new lines to allow paragraphs
         Developed a scalable image processing app on AWS, utilizing EC2 for computation and S3 for storage, achieving rapid processing of 5,000 images in 3.2 minutes. <br>
          - AWS
          - AWS S3,EC2,
          - PEFT
          - accelerate
          - DeepSpeed
      - layout: top-middle
        title: Scalable Social Networking Distributed Database Solutions for High-Performance Applications
        link: https://fingpt.info/
        link_text: <mark>Fin GPT 101</mark>
        additional_links:
          - title:  fingpt.info
            icon: fab fa-github
            url: https://github.com/USFCA-courses/final-project-maneelusf
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   Think of this as your equity research analyst for stocks of the S&P 500.
        description: | # this will include new lines to allow paragraphs
          Developed 'ConnectX', leveraging MongoDB and Cassandra to build a distributed database solution for dynamic social networking platforms. Prioritizing scalability
          and fault tolerance, the project aims to optimize data handling and ensure reliable performance.. The key tools used in this project are:- <br>
                    - MongoDB<br>
                    - MySQL<br>
                    - DynamoDB<br>
                    - Redis<br>
                    - Python<br>
                    - Docker<br>
      - layout: top-middle
        title: Explainability of sequential recommender systems with SHAP values
        # link: github.com/maneelusf/extpersonalization
        # link_text: <mark>SHAPley explanations</mark>
        additional_links:
          - title:  fingpt.info
            icon: fab fa-github
            url: github.com/maneelusf/extpersonalization
        description: | # this will include new lines to allow paragraphs
          As an academic collaboration with Amazon Web Services Machine Learning Solutions, I enabled SHAPLey explanations for sequential recommender systems. Generating explanations 
                    for sequential recommender systems helps identify which events are important in determining the model recommendations. The key tools used in this project are:- <br>
                    - PyTorch<br>
                    - SHAP<br>
                    - Pandas<br>
                    - Numpy<br>
                    - Mlflow<br>
      - layout: top-middle
        title: Reddit and SEC filings sentiment analysis of Rusell 3000 stocks
        # link: https://github.com/gurug-dev/distributed_data_systems_project
        # link_text: <mark>Sentiment Analysis</mark>
        additional_links:
          - title:  fingpt.info
            icon: fab fa-github
            url: github.com/gurug-dev/distributed_data_systems_project
        description: | # this will include new lines to allow paragraphs
          This is a group project where we collected SEC filings(Form 10k Item 7A) on ~1600 stocks as well as reddit posts on 28 subreddits regarding investing.
           We then perform sentiment analysis by using a pretrained HugginFace model. The key tools used in this project are:-.  <br>
                    - Praw<br>
                    - MongoDB<br>
                    - Databricks<br>
                    - PySpark<br>
                    - Huggingface<br>
                    - Airflow<br>
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
    - layout: left
      title: Cisco
      sub_title: Software Engineer II
      caption: April 2021 - July 2022
      quote: >
       As a software engineer at Cisco, I was involved in designing and developing scalable applications for [WebEx Connect](https://cpaas.webex.com/products/webex-connect)
, which includes the Cloud Communications Platform, built for enterprise and digital interactions at scale across the entire customer journey. My role involved working across multiple messaging channels
      description: | # this will include new lines to allow paragraphs
          - Train sequential deep learning recommender models on 3 open-source datasets (ML-1m/Yelp/Amazon Books).
          - Model explainability of recommender system models using KERNELSHAP and extending it to the sequential domain.
    - layout: left
      title: NextEducation 
      link: hypersonix.ai/profit-os
      link_text: Hypersonix
      sub_title: 
      caption: March 2019 - April 2021
      quote: >
        As a senior data scientist, I have executed multiple data science projects in the areas of promotion, pricing & supply chain for customers with annual revenues of > $100M. 
      description: | # this will include new lines to allow paragraphs
        - Developed and implemented a text similarity model utilizing FuzzyWuzzy and Spacy to accurately map customers across three separate Enterprise Resource Planning (ERP) systems with 70% accuracy replacing the manual approach.
        - Designed ETL pipelines for monitoring order statuses and tracking truck movements from distribution centers to stores. Developed a uniform schema across 12 tables, which resulted in 86% of orders being mapped to exact delivery times.
        - Designed a promotion effectiveness model that calculated key drivers of promotion, such as direct lift, halo and cannibalization at the item level. Escalated ~ 5% of promotions on a weekly basis.
        - Calculated optimal inventory levels and replenishment schedules for all SKUs by time series forecasting (FB-Prophet) and Linear Programming techniques (MIP on CPLEX) for better supply chain management.
    - layout: left
      title: TSSPDCL
      sub_title: Software Engineer
      link: https://tgsouthernpower.org/
      link_text: TSSPDCL
      caption: March 2018 - March 2019
      quote: >
        As part of the FP&A team, I was responsible for budgeting,forecasting and presentation of financial statements to the executive leadership. 
      description: | # this will include new lines to allow paragraphs
        - Optimized key monthly task processes by writing a VBA Macro reducing book closure time by 20%.
        - Designed, reported and maintained financial models on working capital, inventory and debtor aging.
    - layout: left
      title: eAutomaton
      sub_title: Software Engineer Intern
      link: https://t-hub.co/
      link_text: eAutomaton-T Hub
      caption: October 2017 - March 2018
      quote: >
        As part of the Corporate Banking Team, I conducted a market research study to identify opportunities for business development and worked on the consolidation of loans for a key client.
      description: | # this will include new lines to allow paragraphs
        - Developed a list of 72 prospective clients by conducting a market study on French and Swedish subsidiaries in India.
        - Examined the loan book of the client to identify opportunities for consolidation & proposed a solution to consolidate a $20M outstanding loan across 55 entities by 400%.
    - layout: left
    

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Arizona State University
        caption: 2022 - 2024
        sub_title: Masters in Computer Science
        description: | # this will include new lines to allow paragraphs
           **Key Courses**:Statistical Machine Learning, Distributed database systems, Software Security, Artificial Intelligence, Data Intensive Systems for Machine Learning
      - layout: top-middle
        title: Birla Institute of Technology & Science,Pilani
        caption: 2012 - 2016
        sub_title: Bachelors in Electrical and Electronics
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      <img src="images/programming.png" width="50" height="50"><mark>Programming Languages</mark>: Python ,Java ,JavaScript ,Scala.<br>
      <img src="images/db.png" width="50" height="50"><mark>Data Engineering & Databases</mark>: Proficient in MySQL,PostgresSQL,MongoDB,Apache Spark,Apache Kafka,Redis,DynamoDB.<br>
      <img src="images/machinelearning.png" width="50" height="50"><mark>Machine Learning Techniques</mark>: Knowledge of decision trees, random forest, linear & logistic regression,linear programming and deep learning(RNNs and GRUs).<br>
      <img src="images/communications.png" width="50" height="50"><mark>Communication</mark>: Skilled in presenting to technical and non-technical audience.<br>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
