# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Vikas Vasireddy
title: Software Engineer / ML Engineer
email: vikasvasireddy264@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  vikasvasireddy01
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: vikasvasireddy
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fa-solid fa-circle-envelope
#   url: vikasvasireddy264@gmail.com

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/avatar3.jpeg
about_content: | # this will include new lines to allow paragraphs
 I am an experienced software engineer with expertise in software engineering and machine learning. I have a proven track record in designing, developing, and scaling microservices, as well as integrating advanced messaging systems and APIs for enhanced data analytics and system performance. 
  Currently, I am a graduate assistant at Arizona State University, focusing on computing on AI and ML. Previously, I worked at Cisco, where I managed the daily dispatch of millions of messages and engineered solutions that significantly improved system responsiveness and scalability.
  On this website, you can learn more about my skills, experience, and interests, and get in touch with me to discuss potential opportunities or collaborations.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Elastic Cloud Image Processing Solution  
        additional_links:
          - title:  fingpt.info
            icon: fab fa-github
            url: https://github.com/USFCA-courses/final-project-maneelusf
          
        description: | # this will include new lines to allow paragraphs
         Developed a scalable image processing app on AWS, utilizing EC2 for computation and S3 for storage, achieving rapid processing of 5,000 images in 3.2 minutes. <br>
          - AWS
          - AWS S3,EC2,
          - PEFT
          - accelerate
          - DeepSpeed
      - layout: top-middle
        title: Scalable Social Networking Distributed Database Solutions for High-Performance Applications
        link: https://fingpt.info/
        link_text: <mark>Fin GPT 101</mark>
        additional_links:
          - title:  fingpt.info
            icon: fab fa-github
            url: https://github.com/USFCA-courses/final-project-maneelusf
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   Think of this as your equity research analyst for stocks of the S&P 500.
        description: | # this will include new lines to allow paragraphs
          Developed 'ConnectX', leveraging MongoDB and Cassandra to build a distributed database solution for dynamic social networking platforms. Prioritizing scalability
          and fault tolerance, the project aims to optimize data handling and ensure reliable performance.. The key tools used in this project are:- <br>
                    - MongoDB<br>
                    - MySQL<br>
                    - DynamoDB<br>
                    - Redis<br>
                    - Python<br>
                    - Docker<br>
      
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
    - layout: left
      title: Cisco
      sub_title: Software Engineer II
      caption: April 2021 - July 2022
      quote: >
       As a software engineer at Cisco, I was involved in designing and developing scalable applications for  <a href="https://cpaas.webex.com/products/webex-connect"> WebEx Connect</a>, which includes the Cloud Communications Platform, built for enterprise and digital interactions at scale across the entire customer journey. My role involved working across multiple messaging channels
      description: | # this will include new lines to allow paragraphs
          - Designed, developed, and scaled microservices for Twitter, Instagram, and Apple Business Chat channels. Managed the daily dispatch of 10+ million messages and emails using SpringBoot and Kafka.
          - Implemented the integration of Kafka with the existing HornetQ messaging system, achieving a 20% reduction in average message latency and a 15% increase in system throughput, significantly enhancing system responsiveness during peak loads.
          - Developed and engineered seamless migration to enterprise Twitter subscriptions, enhancing application capabilities with advanced APIs for richer insights, real-time streaming, and new features, while integrating new APIs and maintaining existing functionalities.
          - Migrated transaction logs from RDS to S3 and implemented AWS Athena queries, achieving substantial cost savings by storing 1TB/month of logs in S3. Implemented minute-wise partition projections, reducing data scan sizes by over 50GB per Athena query for enhanced performance and cost efficiency.
          - Resolved critical timeout issues with RMI protocols, ensuring zero data loss in microservices architecture. Migrated select services to gRPC for improved performance and scalability


    - layout: left
      title: NextEducation 
      link: https://www.nexteducation.in/
      link_text: NextEducation
      sub_title: 
      caption: March 2019 - April 2021
      quote: >
        As a senior data scientist, I have executed multiple data science projects in the areas of promotion, pricing & supply chain for customers with annual revenues of > $100M. 
      description: | # this will include new lines to allow paragraphs
        - Worked on a central system to generate PDF files out of custom templates. Used for generating Fee receipts, Report cards, Payslips etc. Implemented AWS Lambda serverless functions to multiply throughput and reduce processing time. Implemented asynchronous processing using Apache Kafka to increase the responsiveness of the system.
        - Integrated Jaeger for distributed tracing to troubleshoot latency issues. Optimized network connections, achieving a 10x reduction in communication latency. Increased platform capacity to handle concurrent requests by 20x using Apache JMeter, Grafana, InfluxDB, and Glowroot.
        - Implemented Quartz scheduler for monthly payroll cycle generation across 10,000 schools. Engineered asynchronous processing of salary component mapping via Kafka and Maxwell for new staff creation, leveraging Spring Batch.
        - Designed a file upload feature enabling student homework evaluation, utilizing Amazon S3 and BackBlaze cloud storage.
    - layout: left
      title: TSSPDCL
      sub_title: Software Engineer
      link: https://tgsouthernpower.org/
      link_text: TSSPDCL
      caption: March 2018 - March 2019
      quote: >
        As part of the FP&A team, I was responsible for budgeting,forecasting and presentation of financial statements to the executive leadership. 
      description: | # this will include new lines to allow paragraphs
        - Contributed to Energy Billing System (EBS) web app using Spring MVC, developing backend logic in Java, writing SQL queries with JDBC and Hibernate, and ensuring reliability with JUnit tests.
    - layout: left
      title: eAutomaton
      sub_title: Software Engineer Intern
      link: https://t-hub.co/
      link_text: eAutomaton-T Hub
      caption: October 2017 - March 2018
      quote: >
         As part of an early-stage startup focused on Machine Learning and Data Science, I worked as a software engineer, wearing multiple hats even as an intern. I contributed to building the infrastructure and initial product from the ground up using Python and Django, effectively taking the project from 0 to 1.
      description: | # this will include new lines to allow paragraphs
        - Implemented Python-based RESTful APIs using Django and MySQL, incorporating optimized SQL queries, database design, and stored procedures, while leveraging pandas, NumPy, and Matplotlib for efficient data manipulation, analysis,and visualization.
       
    - layout: left
    

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Arizona State University
        caption: 2022 - 2024
        sub_title: Masters in Computer Science
        description: | # this will include new lines to allow paragraphs
           **Key Courses**:Statistical Machine Learning, Distributed database systems, Software Security, Artificial Intelligence, Data Intensive Systems for Machine Learning
      - layout: top-middle
        title: Birla Institute of Technology & Science,Pilani
        caption: 2012 - 2016
        sub_title: Bachelors in Electrical and Electronics
  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      <img src="images/programming.png" width="50" height="50"><mark>Programming Languages</mark>: Python ,Java ,JavaScript ,Scala.<br>
      <img src="images/db.png" width="50" height="50"><mark>Data Engineering & Databases</mark>: Proficient in MySQL,PostgresSQL,MongoDB,Apache Spark,Apache Kafka,Redis,DynamoDB.<br>
      <img src="images/machinelearning.png" width="50" height="50"><mark>Machine Learning Techniques</mark>: Knowledge of decision trees, random forest, linear & logistic regression,linear programming and deep learning(RNNs and GRUs).<br>
      <img src="images/communications.png" width="50" height="50"><mark>Communication</mark>: Skilled in presenting to technical and non-technical audience.<br>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
